### ISSUE TITLE
Error on pip install healpy==1.14.0

### ISSUE THREAD

**Issue by syasini** [healpy/healpy#635]
Hi,

I'm encountering an error when I try to upgrade healpy to v1.14.0. I tried both upgrading from v1.13.0 and installing in a fresh condo environment but none of them work. 

Here's the output of the log file:

```bash
Collecting healpy==1.14.0
  Using cached healpy-1.14.0.tar.gz (4.8 MB)
Requirement already satisfied: matplotlib in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (3.1.2)
Requirement already satisfied: numpy>=1.13 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.19.1)
Requirement already satisfied: six in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.15.0)
Requirement already satisfied: astropy in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (4.0)
Requirement already satisfied: scipy in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.3.0)
Requirement already satisfied: cycler>=0.10 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (2.8.1)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (2.4.7)
Building wheels for collected packages: healpy
  Building wheel for healpy (setup.py): started
  Building wheel for healpy (setup.py): finished with status 'error'
  Running setup.py clean for healpy
Failed to build healpy
Installing collected packages: healpy
  Attempting uninstall: healpy
    Found existing installation: healpy 1.13.0
    Uninstalling healpy-1.13.0:
      Successfully uninstalled healpy-1.13.0
    Running setup.py install for healpy: started
    Running setup.py install for healpy: finished with status 'error'
  Rolling back uninstall of healpy
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/bin/healpy_get_wmap_maps.sh
   from /private/var/folders/kf/wglwk4js7fx8bp4j0qhjclp80000gn/T/pip-uninstall-dsghapgh/healpy_get_wmap_maps.sh
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/healpy-1.13.0.dist-info/
   from /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/~ealpy-1.13.0.dist-info
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/healpy/
   from /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/~ealpy
Collecting healpy==1.14.0
  Using cached healpy-1.14.0.tar.gz (4.8 MB)
Requirement already satisfied: matplotlib in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (3.1.2)
Requirement already satisfied: numpy>=1.13 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.19.1)
Requirement already satisfied: six in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.15.0)
Requirement already satisfied: astropy in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (4.0)
Requirement already satisfied: scipy in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from healpy==1.14.0) (1.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (2.8.1)
Requirement already satisfied: cycler>=0.10 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (1.2.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages (from matplotlib->healpy==1.14.0) (2.4.7)
Building wheels for collected packages: healpy
  Building wheel for healpy (setup.py): started
  Building wheel for healpy (setup.py): finished with status 'error'
  Running setup.py clean for healpy
Failed to build healpy
Installing collected packages: healpy
  Attempting uninstall: healpy
    Found existing installation: healpy 1.13.0
    Uninstalling healpy-1.13.0:
      Successfully uninstalled healpy-1.13.0
    Running setup.py install for healpy: started
    Running setup.py install for healpy: finished with status 'error'
  Rolling back uninstall of healpy
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/bin/healpy_get_wmap_maps.sh
   from /private/var/folders/kf/wglwk4js7fx8bp4j0qhjclp80000gn/T/pip-uninstall-37v9mwdp/healpy_get_wmap_maps.sh
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/healpy-1.13.0.dist-info/
   from /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/~ealpy-1.13.0.dist-info
  Moving to /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/healpy/
   from /Users/siavashyasini/anaconda3/envs/astropaint/lib/python3.7/site-packages/~ealpy
```

**Comment by zonca** [comment]
Mac OS? Have you tried with conda?

**Comment by zonca** [comment]
It looks like you are trying to install from source so make sure you have all the requirements mentioned in the install instructions

**Comment by syasini** [comment]
Thanks for the quick reply Andrea. 

Yes, Mac OS. I'm running `pip install healpy` to fetch it from pypi, not installing from the source file. 

Same command works for v1.13.0 with no problem (also 1.12.9). I'm only getting an error for v1.14.0. 

I just tried `condo install healpy` in a new condo env and it works so I think you're right about the requirements. Have there been new dependencies added since v1.13.0?

**Comment by zonca** [comment]
Yes look in the install docs

**Comment by lpsinger** [comment]
@syasini, you're too fast for us! We haven't uploaded binary wheels for 1.14.0 to PyPI yet. I'm working on that right now.

**Comment by syasini** [comment]
@lpsinger haha sorry Leo. It's because healpy is one of the main dependencies of our mock map simulation package [AstroPaint](https://github.com/syasini/AstroPaint). I'm really looking forward to implementing the new LIC polarization visualization method which is why I was trying to upgrade to 1.14.0. 

Thanks for your explanation! I'll be patient :)

**Comment by lpsinger** [comment]
Done! Please try again with pip.

**Comment by syasini** [comment]
Sorry for the late response Leo. 

I just tried pip installing it in a new condo environment and it's still failing. 
I'm using `pip install healpy --no-cache-dir --force-reinstall` 

Here's the log file: 

[log.txt](https://github.com/healpy/healpy/files/4984486/log.txt)

**Comment by lpsinger** [comment]
It's odd that pip is not trying to install the binary wheel. Maybe the problem is that I built the wheel on a macOS version that is newer than what you are using. What version of macOS do you have?

**Comment by syasini** [comment]
Oh, that might be the case because I haven't updated in a while. I'm still on 10.14.6.

**Comment by lpsinger** [comment]
We really ought to use CI (Travis, GitHub Actions, etc.) to build the wheels, so that we can use the oldest reasonably supported version of macOS.

**Comment by lpsinger** [comment]
If you are able to update to macOS 10.15 (Catalina), then pip will be able to find and use the existing binary wheels on PyPI. If not, then the next release of Healpy will have binary wheels should be compatible with macOS versions as old as 10.9.
