### ISSUE TITLE
rotate_alm appears to work but does not actually modify array for complex64 inputs

### ISSUE THREAD

**Issue by amaurea** [healpy/healpy#702]
When run with a complex128 input, rotate_alm modifies the alm in place:

    alm = healpy.map2alm(np.arange(12))
    print(alm[-1])
    # (-0.6446804787782591+1.16180551552166j)
    healpy.rotate_alm(alm, 1,2,3)
    print(alm[-1])
    # (0.6010602030247686+0.13039042773653065j)

If instead the alm is copmlex64, then everything appears to work. No errors are printed, and the function spends the same time running as normal. But in the end, the alm is not actually updated. This is error prone and can take time to track down the first time.

    alm = healpy.map2alm(np.arange(12)).astype(np.complex64)
    print(alm[-1])
    # (-0.6446805+1.1618055j)
    healpy.rotate_alm(alm, 1,2,3)
    print(alm[-1])
    # (-0.6446805+1.1618055j)

Ideally rotate_alm would support complex64 alms. That would help save memory for large alms, and could be twice as fast. But at the very least it would be useful to get an error message when unsupported data types are used.

I suspect that the issue is that a complex128 copy is created internally and all the work is performed on that copy, leaving the original unchanged.

Tested with healpy 1.14.0.

**Comment by mreineck** [comment]
> I suspect that the issue is that a complex128 copy is created internally and all the work is performed on that copy, leaving the original unchanged.

Yes, that seems very likely. Not absolutely sure what the "best" fix is, but the safest one will probably be to change the interface so that the function always returns a handle to the result array.
Alternatively one could overload the function so that it can directly work on single precision inputs. Unfortunately I have no idea whether this is possibe with a Cython interface.

**Comment by zonca** [comment]
thanks, this is an ugly bug, I fought a couple of hours against Cython and templates without success, so for now I implemented raising an exception in #704. Will keep this issue open if someone wants to try support complex64.

**Comment by mreineck** [comment]
I know it's not much of a consolation at the moment, but if `healpy` should ever switch to `pybind11` for the interface to C++, this sort of problem will just go away. (And a_lm rotation will become much faster too!)

**Comment by ntessore** [comment]
The issue still persists if the array is complex128 but not C contiguous, since the `ascontiguousarray` calls [here](https://github.com/healpy/healpy/blob/eb29716a06ddb65f177d0a09608b0430faadf3a3/healpy/src/_sphtools.pyx#L560-L572) will still return a copy in that case.

Instead of expanding the check to raise the exception, why not add something to the effect of `if ai is not alm[0]: alm[0][:] = ai` etc. to explicitly copy the values back to the input arrays where `ascontiguousarray` created a copy?
