### ISSUE TITLE
ModuleNotFoundError: No module named '_pixelfunc'

### ISSUE THREAD

**Issue by spenczar** [healpy/healpy#867]
In a clean virtualenv, on a M1 macbook with Python 3.11, `pip install healpy` ~the `healpy-1.16.3-cp311-cp311-macosx_12_0_arm64.whl` wheel does not seem to work:~ (note - see my comment below)

```
python3.11 -m venv /tmp/healpy-venv
source /tmp/healpy-venv/bin/activate
pip install pip --upgrade
pip install healpy
python -c "import healpy"
```

The above gives me this output:
```
$ pip install pip --upgrade
Requirement already satisfied: pip in ./healpy-venv/lib/python3.11/site-packages (22.3.1)
Collecting pip
  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.2.1
```
```
$ pip install healpy
Collecting healpy
  Using cached healpy-1.16.3-cp311-cp311-macosx_12_0_arm64.whl
Collecting matplotlib (from healpy)
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/f6/22/9c31044ff7339c63727a135872e5cb59564f11625372a81c3eebf148f4af/matplotlib-3.7.2-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached matplotlib-3.7.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting numpy>=1.13 (from healpy)
  Obtaining dependency information for numpy>=1.13 from https://files.pythonhosted.org/packages/86/a1/b8ef999c32f26a97b5f714887e21f96c12ae99a38583a0a96e65283ac0a1/numpy-1.25.2-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.25.2-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting astropy (from healpy)
  Obtaining dependency information for astropy from https://files.pythonhosted.org/packages/02/33/90ef333965bcf433198de330dbe10898fe9d5b6460c30dbbb7dadf4ab19f/astropy-5.3.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached astropy-5.3.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.4 kB)
Collecting scipy (from healpy)
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/db/8d/6419a5a65a538791f49d52cd8f8883bd11b41df0c9d35f500c9650f1e0b7/scipy-1.11.1-cp311-cp311-macosx_12_0_arm64.whl.metadata
  Using cached scipy-1.11.1-cp311-cp311-macosx_12_0_arm64.whl.metadata (100 kB)
Collecting pyerfa>=2.0 (from astropy->healpy)
  Using cached pyerfa-2.0.0.3-cp311-cp311-macosx_11_0_arm64.whl (333 kB)
Collecting PyYAML>=3.13 (from astropy->healpy)
  Obtaining dependency information for PyYAML>=3.13 from https://files.pythonhosted.org/packages/28/09/55f715ddbf95a054b764b547f617e22f1d5e45d83905660e9a088078fe67/PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (2.1 kB)
Collecting packaging>=19.0 (from astropy->healpy)
  Using cached packaging-23.1-py3-none-any.whl (48 kB)
Collecting contourpy>=1.0.1 (from matplotlib->healpy)
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/88/e3/696e96ee197b1f60242d12b215332af9fc1961c81990c8b5630b89b34ce6/contourpy-1.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached contourpy-1.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.7 kB)
Collecting cycler>=0.10 (from matplotlib->healpy)
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->healpy)
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/32/9a/6fe79bfc6b23f2d5e24a7d9d3402df34128b5df939777d57b94ac8251fa5/fonttools-4.42.0-cp311-cp311-macosx_10_9_universal2.whl.metadata
  Using cached fonttools-4.42.0-cp311-cp311-macosx_10_9_universal2.whl.metadata (150 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib->healpy)
  Using cached kiwisolver-1.4.4-cp311-cp311-macosx_11_0_arm64.whl (63 kB)
Collecting pillow>=6.2.0 (from matplotlib->healpy)
  Obtaining dependency information for pillow>=6.2.0 from https://files.pythonhosted.org/packages/b7/ad/71982d18fd28ed1f93c31b8648f980ebdbdbcf7d8c9c9b4af59290914ce9/Pillow-10.0.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached Pillow-10.0.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting pyparsing<3.1,>=2.3.1 (from matplotlib->healpy)
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil>=2.7 (from matplotlib->healpy)
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib->healpy)
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using cached numpy-1.25.2-cp311-cp311-macosx_11_0_arm64.whl (14.0 MB)
Using cached astropy-5.3.1-cp311-cp311-macosx_11_0_arm64.whl (7.0 MB)
Using cached matplotlib-3.7.2-cp311-cp311-macosx_11_0_arm64.whl (7.3 MB)
Using cached scipy-1.11.1-cp311-cp311-macosx_12_0_arm64.whl (29.5 MB)
Using cached contourpy-1.1.0-cp311-cp311-macosx_11_0_arm64.whl (229 kB)
Using cached fonttools-4.42.0-cp311-cp311-macosx_10_9_universal2.whl (2.7 MB)
Using cached Pillow-10.0.0-cp311-cp311-macosx_11_0_arm64.whl (3.1 MB)
Using cached PyYAML-6.0.1-cp311-cp311-macosx_11_0_arm64.whl (167 kB)
Installing collected packages: six, PyYAML, pyparsing, pillow, packaging, numpy, kiwisolver, fonttools, cycler, scipy, python-dateutil, pyerfa, contourpy, matplotlib, astropy, healpy
Successfully installed PyYAML-6.0.1 astropy-5.3.1 contourpy-1.1.0 cycler-0.11.0 fonttools-4.42.0 healpy-1.16.3 kiwisolver-1.4.4 matplotlib-3.7.2 numpy-1.25.2 packaging-23.1 pillow-10.0.0 pyerfa-2.0.0.3 pyparsing-3.0.9 python-dateutil-2.8.2 scipy-1.11.1 six-1.16.0
```
```
python -c "import healpy"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/healpy-venv/lib/python3.11/site-packages/healpy/__init__.py", line 91, in <module>
    from ._query_disc import query_disc, query_strip, query_polygon, boundaries
  File "healpy/src/_query_disc.pyx", line 10, in init healpy._query_disc
ModuleNotFoundError: No module named '_pixelfunc'
```

I do not get the same error on x86_64 Linux (healpy-1.16.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl).

**Comment by spenczar** [comment]
Oh, this is a bit confused. PyPI doesn't have an arm64 darwin wheel published. So I must have been using one from a local pip cache, previously built from source. 

This is, evidently, a problem with my build of healpy from ` healpy-1.16.3.tar.gz`, not any published wheel.

**Comment by spenczar** [comment]
I guess this is an issue when using `cython 3.0.0`, which was released 2023-07-17.  I was able to resolve this by forcing an old cython version:

```
pip install wheel 'cython<3'
pip install healpy --no-build-isolation --no-cache
```

Perhaps healpy should specify `cython<3` in its build dependencies? Or resolve the underlying issue with Cython, up to you; I don't claim to understand why cython 3+ isn't working.

**Comment by lpsinger** [comment]
This is probably fixed by #862. @zonca, I see a tag for version 1.6.4 but no release. The deployment workflow is triggered by releases, not tags. Would you please create a release using the existing tag?

**Comment by lpsinger** [comment]
@spenczar, @LuKaiXing: Healpy 1.6.4 was just released and should fix this issue. Please update to the latest version of Healpy.

**Comment by spenczar** [comment]
@lpsinger Healpy 1.16.4 was released as binary-only on PyPI (check https://pypi.org/project/healpy/1.16.4/#files) so this is not fixed on M1 macs, where 1.16.3 is still the latest available release, since it must be built from source for this platform.

**Comment by lpsinger** [comment]
@spenczar, the binary-only release was unintentional. See #870.

**Comment by anshul711** [comment]
> 

> 

@spenczar @spenczar  having the exact same issue on my M1. Then I read on readthedocs- 'Note that there are not yet native prebuilt binaries for Apple Silicon Macs.' Is the the cause? and would running above two lines so on my Jupyter environment sort out the problem?

**Comment by lpsinger** [comment]
No, that's not the direct cause. Like I said, the problem is #870. We are working on fixing it.

**Comment by anshul711** [comment]
> No, that's not the direct cause. Like I said, the problem is #870. We are working on fixing it.

HI, Is there any update yet for M1 chips? thanks!

**Comment by lpsinger** [comment]
Unfortunately, GitHub still does not provide free tier macOS arm64 runners, so no.
